### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by nickwang5h** [duxingzhe/IELTS-Reading-Translation#1]
您好，我也是备考雅思的学生，请问一下您这些阅读原文的txt来源。
因为我是CS的学生，所以还想做点关于雅思阅读的nlp处理，所以想用txt版本。
感谢。

**Comment by duxingzhe** [comment]
非常感谢你能关注这个小项目。首先，我的文本来自于其他网站的文本，经过简单编辑以后再上传上github的。目前，我只有PDF版本，也只是扫描版本。不能复制。另外，我曾考过雅思，算是一位曾经的烤鸭。非常高兴看到你能参与到雅思的阅读研究当中。如果你在NLP上对雅思阅读有所分析和研究，欢迎分享。

**Comment by nickwang5h** [comment]
好的，谢谢你的回复=）
